micronaut:
  application:
    name: catalogApi
datasources:
  default:
    url: "jdbc:postgresql://localhost:5452/postgres"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
jpa:
  default:
    entity-scan:
      packages:
        - com.gjug.micronaut.domain
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        enable_lazy_load_no_trans: true
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
