micronaut:
  application:
    name: inventoryApi
  server:
    port: 8085
netty:
  default:
    allocator:
      max-order: 3

#tag::kafka[]
kafka:
  bootstrap:
    servers: localhost:9092
#end::kafka[]

consul:
  client:
    registration:
      enabled: true
